Updates

diff --git a/dot_zprezto/runcoms/zshrc.tmpl b/dot_zprezto/runcoms/zshrc.tmpl
--- a/dot_zprezto/runcoms/zshrc.tmpl
+++ b/dot_zprezto/runcoms/zshrc.tmpl
@@ -12,7 +12,7 @@ fi
 export FZF_DEFAULT_OPTS='--color=fg:#f8f8f2,hl:#bd93f9 --color=fg+:#f8f8f2,hl+:#bd93f9 --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4'
 
 # PATH
-export PATH="/home/stefan/.local/awscli/bin:/home/stefan/.local/awsebcli/bin:/home/stefan/.local/bin:/home/stefan/.pulumi/bin:${PATH}"
+export PATH="/home/stefan/.local/bin:/home/stefan/.pulumi/bin:${PATH}"
 
 # HISTORY
 export HISTSIZE=100000
@@ -26,25 +26,23 @@ setopt hist_ignore_space
 # Default EDITOR
 export EDITOR=nvim
 
+# LS_COLORS
+export LS_COLORS="$(vivid generate one-dark)"
+
+# less
+export LESS="-i -M -R -S -X -z-4"
+
 # bat
 BAT_THEME="Dracula"
 export BAT_STYLE="numbers,changes"
 
 # man
+export MANROFFOPT="-c"
 export MANPAGER="sh -c 'col -bx | bat -l man -p'"
-
-# LESS colors
-export LESS=-R
-export LESS_TERMCAP_me=$(printf '\e[0m')
-export LESS_TERMCAP_se=$(printf '\e[0m')
-export LESS_TERMCAP_ue=$(printf '\e[0m')
-export LESS_TERMCAP_mb=$(printf '\e[0;38;5;217m')
-export LESS_TERMCAP_md=$(printf '\e[0;38;5;147m')
-export LESS_TERMCAP_us=$(printf '\e[0;38;5;217m')
-export LESS_TERMCAP_so=$(printf '\e[0;38;5;229m')
 
 # Set TERM to something the system knows
 export TERM=xterm-256color
+export COLORTERM=truecolor
 
 # ZSH autosuggestions highlight color
 export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=244'
@@ -55,15 +53,21 @@ ZSH_HIGHLIGHT_STYLES[path]=none
 ZSH_HIGHLIGHT_STYLES[path_prefix]=none
 
 # Ansible Vault
-export ANSIBLE_VAULT_IDENTITY_LIST=$(grep 'vault_identity_list' "${HOME}/JobCloud/git/ansible/aws/ansible.cfg" | awk -F ' ' '{print $3}')
+export ANSIBLE_VAULT_IDENTITY_LIST=$(grep 'vault_identity_list' "{{ .work.dir }}/git/ansible/aws/ansible.cfg" | awk -F' ' '{print $3}')
+
+# OpenAI API key
+export OPENAI_API_KEY="{{ .secrets.openAIAPIKey }}"
+
+# Elastic Cloud API key
+export EC_API_KEY="{{ .secrets.elasticCloudAPIKey }}"
 
 # ALIASES
 
 # General aliases
-alias ls='exa -lg'
-alias lt='exa -lT'
-alias la='exa -lga'
-alias l='exa -1'
+alias ls='eza -lg'
+alias lt='eza -lT'
+alias la='eza -lga'
+alias l='eza -1'
 alias vi='nvim'
 alias vim='nvim'
 alias vimdiff='nvim -d'
@@ -75,35 +79,35 @@ alias rm='rm -v'
 alias fd='fd -H --strip-cwd-prefix'
 alias grep='rg -Ni'
 alias g='rg -Ni'
-alias ps='ps faux | g -v ps'
+alias ps='ps faux | rg -v ps'
 alias psg='ps | rg -v rg | g'
 alias ..='cd ..'
 alias ...='cd ../../'
 alias ....='cd ../../../'
 alias .....='cd ../../../../'
+alias zsh-history-reload="fc -R ${HISTFILE:-${ZDOTDIR:-$HOME}/.zsh_history}"
 alias du='du -sh'
 alias df='df -PTh'
-alias cat='bat -P'
+alias cat='bat -P --tabs=2'
 alias watch='viddy'
-alias ping='ping -c 3'
+alias ping='gping'
 alias wget='wget -nv'
-alias curl='curl -s'
 alias mysql='mysql -A -b'
-alias gl='git log -10'
-alias gc='compare_git_commits'
-alias dps='docker ps --format "table {{.ID}}\t{{.Image}}\t{{.Status}}"'
 alias disks='sudo fdisk -l'
-alias ifconfig='ip addr | g inet | g -v "host|inet6" | sed "s/secondary //g"'
-#alias follow='less -S+F'
-alias gfile='cut -d":" -f1 | sort -u'
-alias gproject='gfile | cut -d"/" -f1 | sort -u'
+alias gl='git log -10 --abbrev=16'
+alias dps='docker ps --format "table {{ .zshrc.dpsCmdID }}\t{{ .zshrc.dpsCmdImage }}\t{{ .zshrc.dpsCmdStatus }}"'
 alias gws='rg -i " $|\t"' # grep tabs & spaces at end of lines
 alias gnnl='grep_no_new_line' # grep no new line at end of file
 alias gnbs='rg -e "[\xC2\xA0]" *' # grep non-breaking spaces
-#alias fnbs='for file in $( fd -tf ; fd -tx ) ; do sed -i "s/\xC2\xA0/ /g" "${file}" ; done' # grep non-breaking spaces
+alias gds="ag '(?<!\s)  ' | rg -Niv 'vars_templates|#|mount_devices.sh.j2|chrony.conf|output.sh'" # grep for double spaces from the back
+alias ac='gws ; gnnl ; gds'
 alias ansible-playbook-internal='ansible-playbook --extra-vars "env=internal"'
 alias ansible-playbook-prod='ansible-playbook --extra-vars "env=prod"'
 alias ansible-playbook-qa='ansible-playbook --extra-vars "env=qa"'
+alias pup='verify_torai_session && pulumi preview'
+alias pur='verify_torai_session && pulumi refresh -y'
+alias puu='verify_torai_session && pulumi up -yf'
+alias puc='verify_torai_session && pulumi config'
 
 # Go aliases
 alias gob='go build -ldflags="-s -w"'
@@ -117,7 +121,7 @@ alias pac-update='pacman -Sy'
 alias pac-upgrade='pacman -Su'
 alias pac-install='pacman -S'
 alias pac-remove='pacman -Rsn'
-alias pac-search='pacman -Ss'
+#alias pac-search='pacman -Ss' # see function below
 alias pac-localsearch='pacman -Qs'
 alias pac-info='pacman -Si'
 alias pac-orphans='pacman -Qdt'
@@ -129,10 +133,11 @@ alias arvin='ssh -l stefan 192.168.1.50'
 alias space='ssh -l admin 192.168.1.1'
 
 # Colorized pacman search output
-alias psearch="colorsearch"
+alias pac-search="colorsearch"
 colorsearch () {
 
-  echo -e "$(pacman -Ss $@ | sed \
+  echo -e "$(pacman -Ss ${@} | sed \
+
   -e 's#core/.*#\\033[0;38;5;242m&\\033[0;37m#g' \
   -e 's#extra/.*#\\033[0;38;5;204m&\\033[0;37m#g' \
   -e 's#community/.*#\\033[0;38;5;229m&\\033[0;37m#g' \
@@ -141,11 +146,30 @@ colorsearch () {
 }
 
 # Source bash-helper-functions components
-source ~/JobCloud/git/bash-helpers-library/colors.sh
-source ~/JobCloud/git/bash-helpers-library/aws_functions.sh
-source ~/JobCloud/git/bash-helpers-library/aws_environment.sh
+source {{ .work.dir }}/git/bash-helpers-library/colors.sh
+source {{ .work.dir }}/git/bash-helpers-library/aws_functions.sh
+source {{ .work.dir }}/git/bash-helpers-library/aws_environment.sh
 
-# jobcloud init function (aws sso, ecr, ssh keys)
+# source .zshrc & update history
+reload () {
+
+  source ~/.zshrc
+  zsh-history-reload
+
+}
+
+# less with pygments & bat
+less () {
+
+  if (( ${#} == 0 )) ; then
+    command bat
+  else
+    pygmentize -g -O style=nord-darker "${@}" 2> /dev/null | command bat
+  fi
+
+}
+
+# jobcloud init function
 jc_init () {
 
   echo
@@ -168,13 +192,13 @@ jc_init () {
 
   # aws sso session envvars
   awsAccountId="$(aws configure get sso_account_id --profile ${profile})"
-  awsRegion="$(aws configure get sso_region --profile ${profile})"
+  awsRegion="$(aws configure get region --profile ${profile})"
   awsRole="$(aws configure get sso_role_name --profile ${profile})"
 
   session=$(aws sso get-role-credentials \
     --account-id "${awsAccountId}" \
     --role-name "${awsRole}" \
-    --access-token "$(cat ~/.aws/sso/cache/*.json | jq -r '.accessToken | select( . != null )' | head -1)" \
+    --access-token "$(cat ${HOME}/.aws/sso/cache/*.json | jq -r '.accessToken | select( . != null )' | head -1)" \
     --region "${awsRegion}")
 
   AWS_ACCESS_KEY_ID=$(jq -r '.roleCredentials.accessKeyId' <<< "${session}")
@@ -198,28 +222,27 @@ jc_init () {
   fi ; echo
 
   # AWS console browser session
-  xdg-open 'https://d-936700e7c9.awsapps.com/start#/' 2> /dev/null
+  xdg-open '{{ .aws.startUrl }}#/' 2> /dev/null
 
-  # ssh keys
-  echo -e "\\n${ink_gray}Adding SSH private keys ...${ink_clear}\\n"
-  ssh-add ~/.ssh/ce ; echo
+  echo
 
 }
 source ~/.aws/envvars
 
+# switch session credentials to target account
 aws-session () {
 
   accountName="${1}"
-  binDir="${HOME}/JobCloud/git/cloud-tools/aws-session/bin"
+  binDir="{{ .work.dir }}/git/cloud-tools/aws-session/bin"
   binName="aws-session-linux-amd64"
 
   case "${accountName}" in
     jobcloud)
-      accountId="864261092842" ;;
+      accountId="{{ .aws.accountID1 }}" ;;
     playground)
-      accountId="" ;;
+      accountId="{{ .aws.accountID2 }}" ;;
     torai)
-      accountId="579888146138" ;;
+      accountId="{{ .aws.accountID3 }}" ;;
   esac
 
   if [[ -z "${accountId}" ]] ; then
@@ -228,11 +251,21 @@ aws-session () {
 
   "${binDir}"/"${binName}" \
     -a "${accountId}" \
-    -n AWSAdministratorAccess \
-    -s https://jobcloud-sso.awsapps.com/start \
-    -r eu-west-1
+    -n {{ .aws.role }} \
+    -s {{ .aws.startUrl }} \
+    -r {{ .aws.region }}
 
   source "${HOME}"/.aws/envvars
+
+}
+
+# make sure the current shell uses session credentials from the Torai account
+verify_torai_session () {
+
+  if [[ "$(aws sts get-caller-identity | jq -r '.Account')" != '{{ .aws.accountID3 }}' ]] ; then
+    echo -e "\\n  No Torai session in this shell ...\\n"
+    return 1
+  fi
 
 }
 
@@ -267,7 +300,7 @@ gga [action] [options]
     esac
   done
 
-  rootDir="${HOME}/JobCloud"
+  rootDir="{{ .work.dir }}"
   if [[ -z "${gitPath}" ]] ; then
     gitDir="git"
   else
@@ -321,24 +354,10 @@ gga [action] [options]
 
 }
 
-# git compare two commits for defined repository
-compare_git_commits () {
-
-  # input vars
-  repo="${1}"
-  startCommit="${2}"
-  endCommit="${3}"
-
-  # on linux
-  xdg-open "https://github.com/jobcloud/${repo}/compare/${startCommit}..${endCommit}"
-  # on macos
-  #open "https://github.com/jobcloud/${repo}/compare/${startCommit}..${endCommit}"
-
-}
-
+# check repository for branches without pull requests
 check_lonely_git_branches () {
 
-  repoDir="${HOME}/JobCloud/git"
+  repoDir="{{ .work.dir }}/git"
   repoList=$(ls -1d "${repoDir}"/*)
 
   echo
@@ -377,14 +396,14 @@ ansible_diff () {
 ansible_vault_diff () {
 
   # exit if not in ansible/aws directory
-  if [[ "$(pwd | rev | cut -d'/' -f1:2 | rev)" != "ansible/aws" ]] ; then
+  if [[ "$(pwd | rev | cut -d'/' -f1-2 | rev)" != "ansible/aws" ]] ; then
     echo -e "\\nYou need to be in the ansible/aws directory for the function to work properly\\n"
     return 1
   fi
-  
+
   # fetch list of files that have been changed compared to main
   modifiedFiles=$(git diff --name-status main | awk 'match($1, /A|M/){print $2}' | grep 'aws/' | sed 's/aws\///' | sort)
-  
+
   # filter Ansible Vault files
   vaultFiles=$(
     while IFS= read -r mFile ; do
@@ -413,40 +432,67 @@ ansible_vault_diff () {
 
 }
 
-# parse files in the Ansible repository and replace common variables
-ansible_replace_vars () {
+# helper function to visually verify the WAF rules priority order
+ansible_verify_waf_rules_priority () {
 
-  # static vars
-  groupVars="${HOME}/JobCloud/git/ansible/aws/inventories/group_vars/all.yml"
-  region="$(g region ${groupVars} | g -v 'ecr_prefix' | sed 's/"//g' | cut -d' ' -f2)"
-  account="$(g aws_account ${groupVars} | g -v 'ecr_prefix' | sed 's/"//g' | cut -d' ' -f2)"
+  # exit if not in ansible/aws directory
+  if [[ "$(pwd | rev | cut -d'/' -f1-2 | rev)" != "ansible/aws" ]] ; then
+    echo -e "\\nYou need to be in the ansible/aws directory for the function to work properly\\n"
+    return 1
+  fi
 
-  # input vars
-  file="${1}"
+  filesState="${1}" # committed or uncommitted
 
-  # parse the file
-  sed -e "s/{{ region }}/${region}/g" -e "s/{{ aws_account }}/${account}/g" "${file}" | cat -p -l json --paging=never
+  if [[ "${filesState}" == 'uncommitted' ]] ; then
+    files=$(git diff --name-only | grep '/waf_rules/.*\.json$' | sed 's/aws\///')
+  elif [[ "${filesState}" == 'committed' ]] ; then
+    files=$(git diff --name-only main HEAD | grep '/waf_rules/.*\.json$' | sed 's/aws\///')
+  else
+    echo -e "\\nSupply either 'committed' or 'uncommitted' to the function ..."
+    return 1
+  fi
+
+  for wafRulesJson in ${files} ; do
+    echo -e "\\n${wafRulesJson}:\\n"
+    grep '^      "Priority"' "${wafRulesJson}"
+  done ; echo
 
 }
 
-# update aws cli
-update_aws_cli () {
+# get a fresh Docker environment
+cleanup_docker_environment () {
 
-  # variables
-  installDir="${HOME}/.local/awscli"
-  archiveName="awscliv2.zip"
-  
-  # download latest linux archive
-  curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "${archiveName}"
-  
-  # unzip archive
-  unzip -q "${archiveName}"
-  
-  # update the AWS CLI
-  aws/install --bin-dir "${installDir}/bin" --install-dir "${installDir}" --update
-  
-  # cleanup
-  rm -r aws "${archiveName}" > /dev/null
+  docker stop $(docker ps -aq) 2> /dev/null && docker rm $(docker ps -aq) 2> /dev/null
+  docker system prune -af
+  docker buildx inspect --bootstrap
+
+}
+
+# delete all git branches except the default one
+cleanup_git_branches () {
+
+  # abort if there are uncommitted changes
+  if git status --porcelain | grep -q . ; then
+    echo -e "\\nUncommitted changes detected. Aborting ...\\n"
+    return 1
+  fi
+
+  # determine default branch
+  defaultBranch="$(git branch -r | grep -Po 'HEAD -> \K.*$' | sed 's/origin\///')"
+
+  # checkout default branch
+  git checkout "${defaultBranch}"
+
+  # delete all branches except default one
+  for branch in $(
+    git branch \
+    | grep -v "${defaultBranch}")
+  do
+    git branch -D "${branch}"
+  done
+
+  # show branches
+  git branch
 
 }
 
@@ -465,11 +511,44 @@ fetch_rds_root_password () {
 
 }
 
-# remove string from history
+# remove last command from history
 fail () {
 
-  HISTFILE=/dev/null ; sed -i '$ d' ~/.zsh_history
-  HISTFILE=~/.zsh_history
+  local historyFile="${HOME}/.zsh_history"
+
+  # turn off zsh history temporarily
+  fc -A ; fc -p "${historyFile}" ; unset HISTFILE
+
+  # test for gawk availability & version
+  if ! (command -v gawk > /dev/null) ; then
+    echo -e "\\n  gawk is required for this function to work\\n"
+    return 1
+  fi
+  if [[ "$(gawk --version | gawk 'NR==1 { gsub(/,$/, "", $3); print $3 }')" < '4.1.0' ]] ; then
+    echo -e "\\n  gawk version 4.1.0 or higher is required for this function to work\\n"
+    return 1
+  fi
+
+  # fetch the last command (may be multiline) and remove backslashes before newlines
+  local lastCommand=$(tac "${historyFile}" | gawk '/^: [0-9]+:0;/{if (cmd) exit; cmd=$0; next} {cmd=$0"\n"cmd} END{gsub(/\\\n/, "\n", cmd); print cmd}')
+
+  # remove all occurrences of the last command from history
+  gawk -i inplace -v lastCommand="$lastCommand" '
+  BEGIN { RS=": [0-9]+:0;"; ORS=""; first=1 }
+  {
+    # remove the leading newline from the record separator
+    sub(/^\n/, "", $0);
+    if ($0 != lastCommand) {
+      if (!first) {
+        printf("%s", RS)
+      }
+      printf("%s\n", $0);
+      first=0;
+    }
+  }' "${historyFile}"
+
+  # turn zsh history back on
+  export HISTFILE="${historyFile}" ; fc -P
 
 }
 
@@ -494,6 +573,3 @@ autoload -Uz compinit && compinit
 
 # Completion for AWS CLI
 complete -C /usr/bin/aws_completer aws
-
-# Completion for Serverless
-[ -f ~/.config/tabtab/__tabtab.bash ] && . ~/.config/tabtab/__tabtab.bash || true
